[package]
name = "cssh-remote"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Remote-side executable for cssh"

[[bin]]
name = "cexec"
path = "src/main.rs"

[dependencies]
cssh-common = { path = "../cssh-common" }
tokio = { workspace = true }
thiserror = { workspace = true }
